Strings = {
    wood_blips = 'Wood',
    wood_sell_blips = 'Wood Sales',
    intro_instruction = 'Press ~INPUT_ATTACK~ to cut the wood, ~INPUT_FRONTEND_RRIGHT~ to cancel.',
    wood_cutter = '[E] - Cut the Wood',
    sell_material = '[E] - Sell Material',
    rewarded = 'Cut the Wood',
    rewarded_desc = 'You have succesfully wood 1x'
    sold_for = 'Items Sold',
    sold_for_desc = 'You have sold %sx %s for $%s',
    failed_mine = 'Failed',
    failed_mine_desc = 'You failed to cut the wood!',
    no_axe = 'No Axe',
    no_axe_desc = 'You failed to cut wood'
    axe_broke = 'Axe Broke',
    axe_broke_desc = 'You hit the wood wrong and your axe snapped!',
    cantcarry = 'Can\'t Carry',
    cantcarry_desc = 'No more room to carry 1x',
    possible_cheater = 'Exploit Detected',
    possible_cheater_desc = 'You have been reported to staff.',
    kicked = 'You have been kicked and reported to staff for possible cheating.'
}   